name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - run: npm ci
      - run: npm run lint -- --fix

      # - name: Create PR For Linting Fixes
      #   id: create-pr
      #   uses: peter-evans/create-pull-request@v6

      # - name: Merge Linting Fix PR
      #   uses: juliangruber/merge-pull-request-action@v1.3.1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     number: ${{ steps.create-pr.outputs.pull-request-number }}
      #     method: squash