name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - run: npm ci
      - run: npm run lint -- --fix

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Configure git to use GPG
        run: |
          git config --global user.signingkey 2757FBB7C900FB37AA6D69BD6064375E00334807
          git config --global gpg.program gpg

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          commit: -S "${{ secrets.GPG_PRIVATE_KEY }}"
